#!/usr/bin/env python3
"""
Generates the app icon from one source of truth.

    python3 tools/generate_app_icon.py

Produces:
    res/drawable/ic_launcher_background.xml   adaptive icon, background layer
    res/drawable/ic_launcher_foreground.xml   adaptive icon, foreground layer
    res/drawable/ic_launcher_monochrome.xml   themed icon (Android 13+), one colour

### The mark

A 3x3 block of cells -- the box structure, which is what makes a Sudoku grid
recognisable at a glance. Drawing the full 9x9 grid would be honest and useless:
at launcher size 81 cells collapse into grey mush.

Three cells are filled, on the diagonal. That is not an arbitrary pattern. Boxes
1, 5 and 9 are the only three that share no row, column or box with each other,
which is exactly why GridGenerator seeds them first with three independent
random permutations. The icon draws the one structural fact the generator is
built on.

### Placement

Launcher masks reveal the 72dp circle around the centre of the 108dp grid, so a
square mark may be at most 72/sqrt(2) = 50.9dp across before its corners get
shaved. The block is 50dp, centred -- its corners land just inside that circle,
and the rounded corners give a little more room still.

The empty cells are drawn as filled squares in a lighter navy rather than as
outlines. Strokes scale badly on a themed icon, where the system takes the alpha
channel as a mask and a hairline outline all but disappears; in the monochrome
layer the same distinction is carried by fillAlpha instead.

Their colour was picked by rendering the icon at 48dp, not by eye at full size.
One step above the background (#3C4456) reads fine large and dissolves into the
backdrop small, leaving three floating squares. Two steps (#5A6584) keeps the
block legible but the empty cells then compete with the filled ones and the
diagonal stops reading as the subject. #4A5570 is the one that holds both.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "android-app/app/src/main/res/drawable"

NAVY = "#2B303E"       # background, first colour of the Chessomnia palette
EMPTY = "#4A5570"      # empty cell; see note below on why not darker
BLUE = "#3193C6"       # second colour of the palette
WHITE = "#FFFFFF"

GRID = 108.0
BLOCK = 50.0           # see module docstring: 72/sqrt(2) is the hard ceiling
GAP = 1.75
CELL = (BLOCK - 2 * GAP) / 3
ORIGIN = (GRID - BLOCK) / 2
RADIUS = 3.0

FILLED = {(0, 0): BLUE, (1, 1): WHITE, (2, 2): BLUE}


def num(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def rounded_square(x, y, size, r):
    """A rounded square as pathData -- VectorDrawable has no <rect>."""
    n = num
    return (f"M{n(x + r)},{n(y)} H{n(x + size - r)} A{n(r)},{n(r)} 0 0,1 {n(x + size)},{n(y + r)} "
            f"V{n(y + size - r)} A{n(r)},{n(r)} 0 0,1 {n(x + size - r)},{n(y + size)} "
            f"H{n(x + r)} A{n(r)},{n(r)} 0 0,1 {n(x)},{n(y + size - r)} "
            f"V{n(y + r)} A{n(r)},{n(r)} 0 0,1 {n(x + r)},{n(y)} Z")


def cells():
    """(row, col, pathData) for all nine cells, reading order."""
    for row in range(3):
        for col in range(3):
            x = ORIGIN + col * (CELL + GAP)
            y = ORIGIN + row * (CELL + GAP)
            yield row, col, rounded_square(x, y, CELL, RADIUS)


HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  {what}

  Generated by tools/generate_app_icon.py - do not edit by hand.
-->
"""


def vector(what, paths):
    body = ""
    for entry in paths:
        d, colour = entry[0], entry[1]
        alpha = entry[2] if len(entry) > 2 else None
        body += f'    <path\n        android:pathData="{d}"\n        android:fillColor="{colour}"'
        if alpha is not None:
            body += f'\n        android:fillAlpha="{alpha}"'
        body += " />\n"
    return (HEADER.format(what=what) +
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
            f"{body}</vector>\n")


def write(name, text):
    RES.mkdir(parents=True, exist_ok=True)
    (RES / name).write_text(text)
    print(f"  drawable/{name}  ({len(text)} bytes)")


def main():
    write("ic_launcher_background.xml", vector(
        "Adaptive launcher icon, background layer.",
        [(f"M0,0h{num(GRID)}v{num(GRID)}h-{num(GRID)}z", NAVY)]))

    write("ic_launcher_foreground.xml", vector(
        "Adaptive launcher icon, foreground layer. Sudoku box structure; the three "
        "cells on the diagonal are the boxes that share no unit.",
        [(d, FILLED.get((r, c), EMPTY)) for r, c, d in cells()]))

    # Themed icon: the system tints the whole drawable and reads alpha as a mask,
    # so the filled/empty distinction has to survive as transparency.
    write("ic_launcher_monochrome.xml", vector(
        "Themed icon (Android 13+). One colour; the system tints it.",
        [(d, WHITE, "1.0" if (r, c) in FILLED else "0.4") for r, c, d in cells()]))


if __name__ == "__main__":
    main()
